### ISSUE TITLE
test

### ISSUE THREAD

**Issue by TechStudent11** [KendallDoesCoding/languages-around-the-world#3]
test

**Comment by TechStudent11** [comment]
works

**Comment by KendallDoesCoding** [comment]
@TechStudent11 Thanks for making the issue, I tried to same on my alt, but as I said my account is flagged so it didn't work.. So ig only requirement for it to work, is not to have a account flagged, which more than half of the users don't have...

**Comment by KendallDoesCoding** [comment]
@TechStudent10 you got the achievement coz of this issue lol
