### ISSUE TITLE
[DOCS] Add Contributing Guidelines

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/languages-around-the-world#8]
You have to add Contributing Guidelines:

[Example File in Another repo](https://github.com/KendallDoesCoding/mogul-christmas/blob/main/.github/CONTRIBUTING.md) - Contributing Guidelines

**Comment by frazie** [comment]
I'd like this task assigned to me

**Comment by KendallDoesCoding** [comment]
> I'd like this task assigned to me

Sure

**Comment by KendallDoesCoding** [comment]
waiting for your reply on this @frazie

**Comment by KendallDoesCoding** [comment]
sure!
